### ISSUE TITLE
add option to config balance algorithm

### ISSUE THREAD

**Issue by jiajunhuang** [jiajunhuang/guard#11]
https://github.com/jiajunhuang/guard/pull/9 we've implemented the random algorithm and naive round robin, so we should provide a way to use them.

**Comment by sundy-li** [comment]
And the ratio > 0.3  should be configured.

**Comment by jiajunhuang** [comment]
@sundy-li yes, I will, thank you!

**Comment by jiajunhuang** [comment]
done by https://github.com/jiajunhuang/guard/pull/20
